
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest-spring?useTimezone=true&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8090